[package]
name = "gavin-rust-blog-os"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "gavin-rust-blog-os"
test = false
bench = false
